#
# Module manifest for module 'SystemInfo'
#
# Generated by: Thaddeus
#
# Generated on: 6/24/2026
#
@{
    ModuleVersion   = '6.7'
    Author          = 'Thaddeus Nemeroff'
    Description     = 'Quickly reference system info if you are a PowerShell Geeker who forgot about Task Manager or are remoting in ig'
    RootModule      = 'SystemInfo.psm1'
    FunctionsToExport = @('Get-Uptime', 'Get-DiskSpaceReport', 'Get-MemoryUse')
}
